/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
/**
 * A control panel within the game.
 * 
 * @author h_nan
 */
public class ControlPanel extends javax.swing.JPanel {

    private Game game;

    /**
     * Creates new form ControlPanel
     * @param game The current game.
     */
    public ControlPanel(Game game) {
        initComponents();
        this.game = game;
        volumeSpinner.setValue(game.getVolume());
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restartButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        levelsComboBox = new javax.swing.JComboBox<>();
        pauseButton = new javax.swing.JToggleButton();
        muteButton = new javax.swing.JToggleButton();
        volumeSpinner = new javax.swing.JSpinner();
        volumeLabel = new javax.swing.JLabel();

        restartButton.setText("Restart");
        restartButton.setActionCommand("jButton1");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        levelsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        levelsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelsComboBoxActionPerformed(evt);
            }
        });

        pauseButton.setActionCommand("Pause");
        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        muteButton.setText("Mute");
        muteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteButtonActionPerformed(evt);
            }
        });

        volumeSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.1d));
        volumeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSpinnerStateChanged(evt);
            }
        });

        volumeLabel.setText("Volume");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeLabel)
                .addGap(14, 14, 14)
                .addComponent(volumeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(levelsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(levelsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(restartButton)
                        .addComponent(quitButton)
                        .addComponent(pauseButton)
                        .addComponent(muteButton)
                        .addComponent(volumeLabel)
                        .addComponent(volumeSpinner)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        game.restart();
    }//GEN-LAST:event_restartButtonActionPerformed

    private void levelsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelsComboBoxActionPerformed
        String jComboBox1Selected = (String) levelsComboBox.getSelectedItem();
        if ("Level 1".equals(jComboBox1Selected)) {
            game.goLevel1();
        }

        if ("Level 2".equals(jComboBox1Selected)) {
            game.goLevel2();
        }

        if ("Level 3".equals(jComboBox1Selected)) {
            game.goLevel3();
        }
    }//GEN-LAST:event_levelsComboBoxActionPerformed

    private void volumeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSpinnerStateChanged
        double spinnerValue = (double) volumeSpinner.getValue();
        Game.getSound().setVolume(spinnerValue);
    }//GEN-LAST:event_volumeSpinnerStateChanged

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        game.stopGame();
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        //        System.exit(0);
        System.out.println("Thanks for playing!");
    }//GEN-LAST:event_quitButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if (pauseButton.isSelected()) {
            game.pause();
        } else {
            game.resume();
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void muteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteButtonActionPerformed
        // TODO add your handling code here:
        if (muteButton.isSelected()) {
            Game.getSound().setVolume(0.0001);
        } else {
            Game.getSound().setVolume(0.2);
        }
    }//GEN-LAST:event_muteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> levelsComboBox;
    private javax.swing.JToggleButton muteButton;
    private javax.swing.JToggleButton pauseButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartButton;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSpinner volumeSpinner;
    // End of variables declaration//GEN-END:variables
}
